seq_len: 512
pred_len: 720
sl_epochs: 100
sl_batch_size: 32
lr: 1e-4
patience: 10
train_split: 0.6
test_split: 0.2
num_channels: 21
num_workers: 8
scheduler: None
data: "custom"
root_path: "../../../data/"
data_path: "weather.csv"
learning_type: "sl"
num_enc_layers: 3
d_model: 128
d_ff: 256
num_heads: 16
attn_dropout: 0.2
ff_dropout: 0.2
pred_dropout: 0.0
run_id: "patchtst_weather_512_720"
best_model_path: "checkpoint/weather_512_720"

early_stopping : True