model_id: "PatchTSTBlind"
seq_len: 512
pred_len: 96
sl_epochs: 100
sl_batch_size: 32
lr: 1e-4
patience: 10
train_split: 0.6
test_split: 0.2
num_channels: 862
num_workers: 8
criterion: "MSE"
scheduler: "None"
data: "custom"
root_path: "../../../data/"
data_path: "traffic.csv"
learning_type: "sl"
num_enc_layers: 3
d_model: 128
d_ff: 256
attn_dropout: 0.2
ff_dropout: 0.2
num_heads: 16
pred_dropout: 0.0
early_stopping : True
exp_id: "patchtst_patchtstblind_traffic_512_96"
best_model_path: "checkpoint/traffic_512_96/patchtst"

