model_id: "PatchTSTBlind"
seq_len: 512
pred_len: 96
sl_epochs: 100
sl_batch_size: 32
lr: 1e-4
patience: 10
train_split: 0.6
test_split: 0.2
num_channels: 7
num_workers: 8
scheduler: None
data: "ETTm2"
root_path: "../../../data/"
data_path: "ETTm2.csv"
learning_type: "sl"
num_enc_layers: 3
d_model: 128
d_ff: 256
num_heads: 16
attn_dropout: 0.2
ff_dropout: 0.2
pred_dropout: 0.0
early_stopping : True
exp_id: "patchtst_patchtstblind_ettm2_512_96"
best_model_path: "checkpoint/ettm2_512_96/patchtst"
api_token : eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJjZmVlNDAxMS1hOTQyLTQ0MjUtODliNi1iZTkzOTVmMTI1OTUifQ==
