model_id: "PatchTSTBlind"
criterion: "MSE"
optim_type: "adam"
learning_type: "sl"
seq_len: 512
pred_len: 96
sl_epochs: 100
sl_batch_size: 32
lr: 1e-4
early_stopping: True
patience: 10
train_split: 0.6
test_split: 0.2
num_channels: 321
num_workers: 8
scheduler: None
data: "custom"
root_path: "../../../data/"
data_path: "electricity.csv"
num_enc_layers: 3
d_model: 128
d_ff: 256
num_heads: 16
attn_dropout: 0.2
ff_dropout: 0.2
pred_dropout: 0.0
exp_id: "patchtst_patchtstbline_electricity_512_96"
best_model_path: "checkpoint/electricity_512_96/patchtst"

